name: "GET CLOUDFLARE-IP-Address"

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 */2 * * *"

jobs:
  runscript:
    name: Get-Cloudflare-IP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Bash Script and Commit Changes
        run: |
          bash get-cloudflare.sh > cloudflare-list.rsc
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automatic update: $(date)"

      - name: Push changes
        run: |
          git remote set-url origin https://${{ secrets.GGHCR_TOKEN }}@github.com/ChosoMeister/Mikrotik-CLOUDFLARE-IP-List.git
          git push
